# Generated by Django 2.2.2 on 2019-07-31 20:41

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='adherence',
            field=jsonfield.fields.JSONField(default=''),
            preserve_default=False,
        ),
    ]
